name = "web-app-starter-pack"
compatibility_date = "2024-01-01"
main = "worker/index.ts"

# Development server configuration
[dev]
port = 8787  # Fixed port for predictable local development

# Serve the frontend build as static assets
[assets]
directory = "./dist"
not_found_handling = "single-page-application"

# D1 Database binding
# TODO: Replace with your database ID after running 'wrangler d1 create app-database'
[[d1_databases]]
binding = "DB"
database_name = "starter-pack"
database_id = "c8403398-e2fc-4a7e-9505-e1e7d11f3a40"

# Optional: KV namespace for caching
# [[kv_namespaces]]
# binding = "CACHE"
# id = "YOUR_KV_NAMESPACE_ID"

# Optional: R2 bucket for file storage
# [[r2_buckets]]
# binding = "BUCKET"
# bucket_name = "your-bucket-name"

# Environment-specific configuration
[env.development]
name = "web-app-starter-pack-dev"
vars = { NODE_ENV = "development" }

[env.staging]
name = "web-app-starter-pack-staging"
vars = { NODE_ENV = "staging" }

[env.production]
name = "web-app-starter-pack"
vars = { NODE_ENV = "production" }